name: wayland_connect_android
description: Transform your Android into a wireless touchpad and remote for Linux.
version: 1.0.3+6
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^12.3.0
  uuid: ^4.5.2
  android_id: ^0.5.1
  shared_preferences: ^2.5.4
  palette_generator: ^0.3.3+7
  cached_network_image: ^3.4.1
  http: ^1.2.2
  sensors_plus: ^6.0.1
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  flutter_local_notifications: ^20.0.0
  flutter_background_service: ^5.1.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
