name: wayland_connect_android
description: Transform your Android into a wireless touchpad and remote for Linux.
version: 1.0.1.1+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  device_info_plus: ^12.3.0
  uuid: ^4.5.2
  android_id: ^0.5.1
  shared_preferences: ^2.5.4
  palette_generator: ^0.3.3+7
  cached_network_image: ^3.4.1
  http: ^1.2.2
  sensors_plus: ^6.0.1
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  flutter_local_notifications: ^20.0.0
  flutter_background_service: ^5.1.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  image_picker: ^1.2.1
  flutter_colorpicker: ^1.1.0
  msgpack_dart: ^1.0.0
  crypto: ^3.0.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
