[package]
name = "wayland_share_screen"
version = "0.1.0"
edition = "2021"

[dependencies]
ashpd = { version = "0.8", features = ["pipewire"] }
pipewire = "0.8"
tokio = { version = "1", features = ["full"] }
zbus = "4"
log = "0.4"
env_logger = "0.11"
libspa = "0.8"
futures = "0.3"
